### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by Valdouz** [Le-Trefle-2-0/Website#4]
![Screenshot_2023-05-03-18-21-36-762_com android chrome](https://user-images.githubusercontent.com/55506883/235979207-0e91c57a-5a1c-4990-acd2-1af485361a9e.jpg)
![Screenshot_2023-05-03-18-21-39-130_com android chrome](https://user-images.githubusercontent.com/55506883/235979210-f85d9cfd-842c-4afa-9884-257550a39c25.jpg)

The text "Descendez pour en avoir plus" goes in the navbar when you scroll the page.

Resolution : 1080x2400 (I think)

**Comment by Nininanou16** [comment]
fixed by https://github.com/Le-Trefle-2-0/Website/commit/e9a5310e26139266095ff0867e9ba99c031eafab, not a responsive issue btw
